export const ErrorCode = Object.freeze({
    INVALID_URL: "INVALID_URL",
    INVALID_EMAIL: "INVALID_EMAIL",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    INVALID_FIELD: "INVALID_FIELD",
    MISSING_FIELD: "MISSING_FIELD",
    NO_ANSWER_FOUND: "NO_ANSWER_FOUND",
    EXTERNAL_API_FAILURE: "EXTERNAL_API_FAILURE",
    SERVER_ERROR: "SERVER_ERROR",
    ITEM_EXISTED: "ITEM_EXISTED",
    ITEM_NOT_FOUND: "ITEM_NOT_FOUND",
})